### ISSUE TITLE
安装了you-get后，出现了下面的界面，它显示的那个错误是怎么回事啊？

### ISSUE THREAD

**Issue by panjinhua** [twlz0ne/you-get_install#1]
python:can't open file 'you-get/you-get-master/you-get': [Errno 2] No such file or directory

**Comment by twlz0ne** [comment]
(幸好我的古董 windows 电脑还没扔掉😄)

你看看安装目录下的 `you-get.zip` 文件大小是不是 <b>0kb</b>。是的话就是墙的原因，你通过浏览器下载 https://github.com/soimort/you-get/archive/master.zip 这个文件，重命名为 `you-get.zip`，替换 <b>0kb</b> 的那个文件。然后重新点击 `you-get.bat` (应该能看见解压过程)，然后就可以了。
